// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReactDOMRe         from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact        from "reason-react/lib/es6/src/ReasonReact.js";
import * as Root$ReactTemplate from "./Root.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Root$ReactTemplate.make(/* array */[])), "index");

export {
  
}
/*  Not a pure module */
