// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry       from "bs-platform/lib/es6/curry.js";
import * as React       from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Root");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  onClick: Curry._1(self[/* handle */0], handleClick)
                }, "message");
    });
  return newrecord;
}

export {
  component   ,
  handleClick ,
  make        ,
  
}
/* component Not a pure module */
